name: Demonstration
on: push

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '25.0.0'
      - uses: oven-sh/setup-bun@v2
      - name: Install JS dependencies
        run: bun install
      - name: JSON.parse use-cases
        run: bun run demo:json
      - name: SyntaxError vs proposed return value
        run: bun run demo:errors
      - name: Overhead of intermediate strings
        run: bun run demo:decoding
      - name: Memory usage with intermediate string
        run: bun run demo:gc-strings
      - name: Compare await new Response(buffer).json() and JSON.parse(buffer.toString())
        run: bun run demo:against-response
